### ISSUE TITLE
Не перехватывается исключительная ситуация с начальным балансом больше максимального

### ISSUE THREAD

**Issue by Gipotolamus** [Kris-i-kris/javaqa-team-diplom-2#14]
# Описание
Нет исключительной ситуации при начальном балансе больше максимального

# Локация дефекта
https://github.com/Kris-i-kris/javaqa-team-diplom-2/blob/b00aa5161d40f1daf32b31aa68326ec9a537272f/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L22

# Шаги воспроизведения
1.  Открыть [код программы](https://github.com/Kris-i-kris/javaqa-team-diplom-2/blob/main/src/main/java/ru/netology/javaqadiplom/SavingAccount.java) в IDEA
1.  Создать объект класса SavingAccount 
1.  Выставить начальный баланс больше максимального
1.  Запустить код
1.  Посмотреть вывод в консоли

*Ожидаемый результат:* Ошибка  перехватывается, код программы продолжает работу.
*Фактический результат:*  Исключительная ситуация IllegalArgumentException не перехватывается, выскакивает сообщение о ошибке, программа останавливается. 

# Тест
https://github.com/Kris-i-kris/javaqa-team-diplom-2/blob/4ed16eeab89e5731309897427c54f6463916021f/src/test/java/ru/netology/javaqadiplom/SavingAccountTest.java#L176-L185

# Окружение

* **Операционная система:** Windos 10 версии 22H2
* **IDEA:** IntelliJ IDEA 2023.2 (Ultimate Edition)
* **Java:** OpenJDK 11

**Comment by Kris-i-kris** [comment]
https://github.com/Kris-i-kris/javaqa-team-diplom-2/blob/4352a66503df42731682f7d49d140063ca5082f0/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L50-L54
