### ISSUE TITLE
Баланс уходит в минус при списании большей суммы чем на счете

### ISSUE THREAD

**Issue by Gipotolamus** [Kris-i-kris/javaqa-team-diplom-2#2]
# Описание
Баланс уходит в минус при списании большей суммы чем на счете

# Локация дефекта
https://github.com/Kris-i-kris/javaqa-team-diplom-2/blob/a010699eb8affbd23c65af8055f7b01ddd269302/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L46

# Шаги воспроизведения
1.  Открыть [код программы](https://github.com/Kris-i-kris/javaqa-team-diplom-2/blob/saving/src/main/java/ru/netology/javaqadiplom/SavingAccount.java) в IDEA
1.  Создать объект класса SavingAccount 
1.  Выставить начальный баланс в 2_000
1.  Произвести оплату на сумму 3_000
1.  Посмотреть вывод в консоли

*Ожидаемый результат:* Отсутствие списания денежных средств из-за превышения суммы баланса
*Фактический результат:*  Со счета списывается сумма превышающая баланс, тем самым уводя счет клиента в минус

# Тест
https://github.com/Kris-i-kris/javaqa-team-diplom-2/blob/4ed16eeab89e5731309897427c54f6463916021f/src/test/java/ru/netology/javaqadiplom/SavingAccountTest.java#L10-L16

# Окружение

* **Операционная система:** Windos 10 версии 22H2
* **IDEA:** IntelliJ IDEA 2023.2 (Ultimate Edition)
* **Java:** OpenJDK 11

**Comment by Kris-i-kris** [comment]
https://github.com/Kris-i-kris/javaqa-team-diplom-2/blob/1a3653f36c345fcfbbb264a30da645acd8dc821e/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L55-L66
