### ISSUE TITLE
Не складывает сумму пополнения и текущий баланс

### ISSUE THREAD

**Issue by Gipotolamus** [Kris-i-kris/javaqa-team-diplom-2#3]
# Описание
Вместо сложения текущего баланса на счете и суммы пополнения, на счете сохраняется только сумма пополнения

# Локация дефекта
https://github.com/Kris-i-kris/javaqa-team-diplom-2/blob/b00aa5161d40f1daf32b31aa68326ec9a537272f/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L68

# Шаги воспроизведения
1.  Открыть [код программы](https://github.com/Kris-i-kris/javaqa-team-diplom-2/blob/main/src/main/java/ru/netology/javaqadiplom/SavingAccount.java) в IDEA
1.  Создать объект класса SavingAccount 
1.  Выставить начальный баланс в 2_000
1.  Произвести пополнение на сумму 3_000
1.  Посмотреть вывод в консоли

*Ожидаемый результат:* Баланс счета составляет сложение первичного баланса и суммы пополнения = 5_000
*Фактический результат:*  Баланс счета составляет сумма пополнения = 3_000

# Тест
https://github.com/Kris-i-kris/javaqa-team-diplom-2/blob/4ed16eeab89e5731309897427c54f6463916021f/src/test/java/ru/netology/javaqadiplom/SavingAccountTest.java#L57-L64

# Окружение

* **Операционная система:** Windos 10 версии 22H2
* **IDEA:** IntelliJ IDEA 2023.2 (Ultimate Edition)
* **Java:** OpenJDK 11

**Comment by Kris-i-kris** [comment]
![10](https://github.com/Kris-i-kris/javaqa-team-diplom-2/assets/138568517/8056e1ee-9a44-4554-a4ce-cb89d62b0685)
![11](https://github.com/Kris-i-kris/javaqa-team-diplom-2/assets/138568517/490eac9e-45a7-4e25-8a5b-19509d9fa99c)
