### ISSUE TITLE
Не добавляет сумму пополнения в рамках верхнего лимита

### ISSUE THREAD

**Issue by Gipotolamus** [Kris-i-kris/javaqa-team-diplom-2#4]
# Описание
Вместо сложения текущего баланса на счете и суммы пополнения, на счете сохраняется только сумма первоначального баланса

# Локация дефекта
https://github.com/Kris-i-kris/javaqa-team-diplom-2/blob/b00aa5161d40f1daf32b31aa68326ec9a537272f/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L68

# Шаги воспроизведения
1.  Открыть [код программы](https://github.com/Kris-i-kris/javaqa-team-diplom-2/blob/main/src/main/java/ru/netology/javaqadiplom/SavingAccount.java) в IDEA
1.  Создать объект класса SavingAccount 
1.  Выставить начальный баланс в 2_000
1.  Произвести пополнение на сумму 8_000
1.  Посмотреть вывод в консоли

*Ожидаемый результат:* Баланс счета составляет сложение первичного баланса и суммы пополнения = 10_000
*Фактический результат:*  Баланс счета составляет начальную сумму = 2_000. Пополнение не прошло

# Тест
https://github.com/Kris-i-kris/javaqa-team-diplom-2/blob/4ed16eeab89e5731309897427c54f6463916021f/src/test/java/ru/netology/javaqadiplom/SavingAccountTest.java#L67-L73

# Окружение

* **Операционная система:** Windos 10 версии 22H2
* **IDEA:** IntelliJ IDEA 2023.2 (Ultimate Edition)
* **Java:** OpenJDK 11

**Comment by Kris-i-kris** [comment]
https://github.com/Kris-i-kris/javaqa-team-diplom-2/blob/1a3653f36c345fcfbbb264a30da645acd8dc821e/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L81-L91
