### ISSUE TITLE
В кредитном счете при ставке <= 0 не перехватывается исключение 

### ISSUE THREAD

**Issue by Kris-i-kris** [Kris-i-kris/javaqa-team-diplom-2#6]
# Описание
При сознании кредитного счета с отрицательной ставкой ожидаемое исключение не перехватывается,  программа останавливает работу.

# Локализация дефекта
https://github.com/Kris-i-kris/javaqa-team-diplom-2/blob/2d73d05f6a30eccebac3aca8f2431d58d3122c6d/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L22

# Шаги воспроизведения

1. Открыть [код программы](https://github.com/Kris-i-kris/javaqa-team-diplom-2.git) в IDEA
2. Прейти в test => CreditAccoutnTest => тест rateLessThanZero
3. Выставить данные initialBalance(начальный баланс) 0
4. creditLimit (максимальная сумма долга банку) 5_000
5. rate(ставка) -1
6. Запустить программу
7. Посмотреть на вывод в консоли

*Ожидаемый результат*  Тест прошел о чем свидетельствует зеленая галочка на консоли. Исключительная ситуация перехвачена. 
*Фактический результат* Окно консоли горит красной надписью о неверно введенных данных. 

# Скриншот
![1](https://github.com/Kris-i-kris/javaqa-team-diplom-2/assets/138568517/1cdf4ab1-f3fb-4f78-961a-af2ff323a864)

# Тест
https://github.com/Kris-i-kris/javaqa-team-diplom-2/blob/4df3a25043171f2db0244f6240fb4eff834d1d5a/src/test/java/ru/netology/javaqadiplom/CreditAccountTest.java#L27-L38

# Окружение
* **Операционная система:** Windos 10 Pro Версия 22H2
* **IDEA:** IntelliJ IDEA 2023.2.1
* **Java:** OpenJDK 11

**Comment by Gipotolamus** [comment]
исправлено
