### ISSUE TITLE
В кредитном счете при изменении ставки <= 0 не вызывается исключение 

### ISSUE THREAD

**Issue by Kris-i-kris** [Kris-i-kris/javaqa-team-diplom-2#7]
# Описание
После создания кредитного счета с параметрами удовлетворяющими требованиям, можно изменить  ставку на отрицательную - которая обойдет метод вызова исключения, и продолжит выполнение расчетов.
Данные удовлетворяющие требованиям выставлены по умолчанию: 
- initialBalance(начальный баланс) 0;
- creditLimit (максимальная сумма долга банку) 5_000;
- rate(ставка) 15;

# Локализация дефекта
https://github.com/Kris-i-kris/javaqa-team-diplom-2/blob/4df3a25043171f2db0244f6240fb4eff834d1d5a/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L20-L21

# Шаги воспроизведения

1. Открыть [код программы](https://github.com/Kris-i-kris/javaqa-team-diplom-2.git) в IDEA
2. Прейти в test => CreditAccoutnTest => тест rateChangedLessThanZeroCheckInMethod
3. В тесте меняем данные ставки (setRate) на (-1).
4. Запускаем программу
5. Посмотреть на вывод в консоли

*Ожидаемый результат*  Данные изменены и не удовлетворяют требованиям системы. Исключительная ситуация перехвачена. Тест прошел (зеленая галочка на консоли).. 
*Фактический результат* Окно консоли горит красной надписью, о том что исключительной ситуации не было.
Через отладчик видно что после изменения данных, мы не возвращаемся к конструктору с предвиденным исключением , а продолжаем выполнять вызванный метод

# Скриншот
![2](https://github.com/Kris-i-kris/javaqa-team-diplom-2/assets/138568517/cfb5409f-e871-47d0-baae-7fd0b0b361f1)
![2,1](https://github.com/Kris-i-kris/javaqa-team-diplom-2/assets/138568517/fb1b1e99-012c-4ff4-a136-c83c38341b94)

# Тест
https://github.com/Kris-i-kris/javaqa-team-diplom-2/blob/4df3a25043171f2db0244f6240fb4eff834d1d5a/src/test/java/ru/netology/javaqadiplom/CreditAccountTest.java#L40-L47

# Окружение
* **Операционная система:** Windos 10 Pro Версия 22H2
* **IDEA:** IntelliJ IDEA 2023.2.1
* **Java:** OpenJDK 11

**Comment by Gipotolamus** [comment]
исправлено
