### ISSUE TITLE
В кредитном счете превышается лимит.

### ISSUE THREAD

**Issue by Kris-i-kris** [Kris-i-kris/javaqa-team-diplom-2#8]
# Описание
Возможность совершить покупку по стоимости большую чем баланс (начальный баланс + кредитный лимит).

Данные удовлетворяющие требованиям выставлены по умолчанию:

initialBalance(начальный баланс) 0;
creditLimit (максимальная сумма долга банку) 5_000;
rate(ставка) 15;

# Локализация дефекта
https://github.com/Kris-i-kris/javaqa-team-diplom-2/blob/2d73d05f6a30eccebac3aca8f2431d58d3122c6d/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L42

# Шаги воспроизведения
1.Открыть [код программы](https://github.com/Kris-i-kris/javaqa-team-diplom-2.git) в IDEA
2.Прейти в test => CreditAccoutnTest => тест purchaseInvalidBorderLimit1
3.В тесте совершаем покупку на account.pay(5_001) превышающую лимит 
4.Запускаем программу
5.Смотрим на вывод в консоли

*Ожидаемый результат:* Баланс не изменился, сумма не списалась
*Фактический результат:* Баланс уменьшился на сумму покупки превышая установленный лимит.

# Скриншот

![3](https://github.com/Kris-i-kris/javaqa-team-diplom-2/assets/138568517/192f1d17-dc11-4501-a1d7-7e2f1f3b471c)

# Тест
https://github.com/Kris-i-kris/javaqa-team-diplom-2/blob/4df3a25043171f2db0244f6240fb4eff834d1d5a/src/test/java/ru/netology/javaqadiplom/CreditAccountTest.java#L64-L69

# Окружение
* **Операционная система:** Windos 10 Pro Версия 22H2
* **IDEA:** IntelliJ IDEA 2023.2.1
* **Java:** OpenJDK 11

**Comment by Gipotolamus** [comment]
исправлено
